"""Database models for the C2 engine.

Uses SQLAlchemy 2.0 async with PostGIS via GeoAlchemy2.
"""

from datetime import datetime, timezone

from geoalchemy2 import Geometry
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class TrackUpdate(Base):
    """Every position update from any sensor source.

    Time-series table -- this is the core data.
    """

    __tablename__ = "track_updates"

    id = Column(Integer, primary_key=True, autoincrement=True)
    entity_id = Column(
        String(64), index=True, nullable=False,
    )  # e.g. "AIS-211234567", "ADSB-4CA7B5"
    source = Column(
        String(32), nullable=False,
    )  # "ais", "adsb", "mavlink", "cot", "manual"
    timestamp = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Position (PostGIS point)
    position = Column(Geometry("POINT", srid=4326), nullable=True)
    latitude = Column(Float)
    longitude = Column(Float)
    altitude_m = Column(Float, default=0.0)

    # Kinematics
    heading = Column(Float, default=0.0)
    speed_mps = Column(Float, default=0.0)
    vertical_rate_mps = Column(Float, default=0.0)

    # Source-specific fields stored as JSON
    raw_data = Column(JSON, default=dict)

    __table_args__ = (
        Index("ix_track_updates_entity_time", "entity_id", "timestamp"),
        Index("ix_track_updates_time", "timestamp"),
    )


class Entity(Base):
    """A resolved entity -- the fused identity of something in the picture.

    Multiple TrackUpdates from different sources can point to the same Entity.
    """

    __tablename__ = "entities"

    id = Column(String(64), primary_key=True)  # e.g. "ENT-a8f3b2c1"
    domain = Column(
        String(16), nullable=False,
    )  # "air", "sea", "land", "subsurface"
    entity_type = Column(String(32), default="unknown")

    # Identity
    name = Column(String(128), default="")
    callsign = Column(String(64), default="")

    # Source identifiers (for correlation)
    mmsi = Column(Integer, nullable=True, index=True)
    icao_hex = Column(String(8), nullable=True, index=True)
    mavlink_sysid = Column(Integer, nullable=True)

    # Classification (latest)
    affiliation = Column(String(16), default="unknown")
    threat_level = Column(Integer, default=0)
    threat_category = Column(String(16), default="none")
    confidence = Column(Float, default=0.5)

    # Latest position (denormalized for fast queries)
    last_position = Column(Geometry("POINT", srid=4326), nullable=True)
    last_latitude = Column(Float, default=0.0)
    last_longitude = Column(Float, default=0.0)
    last_altitude_m = Column(Float, default=0.0)
    last_heading = Column(Float, default=0.0)
    last_speed_mps = Column(Float, default=0.0)
    last_seen = Column(DateTime(timezone=True))
    first_seen = Column(DateTime(timezone=True))

    # Metadata
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Source-specific data
    metadata_ = Column("metadata", JSON, default=dict)


class Classification(Base):
    """Classification history -- every classification decision is recorded."""

    __tablename__ = "classifications"

    id = Column(Integer, primary_key=True, autoincrement=True)
    entity_id = Column(
        String(64), ForeignKey("entities.id"), nullable=False, index=True,
    )
    timestamp = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )

    affiliation = Column(String(16))
    threat_level = Column(Integer)
    threat_category = Column(String(16))
    confidence = Column(Float)
    reasoning = Column(JSON, default=list)  # List of reasoning strings
    anomalies = Column(JSON, default=list)  # List of anomaly dicts

    __table_args__ = (
        Index("ix_classifications_entity_time", "entity_id", "timestamp"),
    )


class Alert(Base):
    """Alerts generated by the engine."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    entity_id = Column(
        String(64), ForeignKey("entities.id"), nullable=True,
    )
    alert_type = Column(
        String(32), nullable=False,
    )  # "emergency", "threat", "anomaly", "info"
    severity = Column(Integer, default=5)  # 1-10
    title = Column(String(256), nullable=False)
    description = Column(Text, default="")

    # State
    acknowledged = Column(Boolean, default=False)
    acknowledged_by = Column(String(64), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)

    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )

    __table_args__ = (
        Index("ix_alerts_type_sev", "alert_type", "severity"),
        Index("ix_alerts_created", "created_at"),
    )


class AuditLog(Base):
    """Immutable audit trail -- every significant action."""

    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    actor = Column(
        String(64), default="system",
    )  # "system", user ID, or service name
    action = Column(
        String(64), nullable=False,
    )  # "classify", "alert", "task_assign", "config_change"
    target_type = Column(String(32), nullable=True)  # "entity", "alert", "task"
    target_id = Column(String(64), nullable=True)
    details = Column(JSON, default=dict)

    __table_args__ = (
        Index("ix_audit_time", "timestamp"),
        Index("ix_audit_actor", "actor"),
    )
