"""LLM-powered intelligence features.

Uses Claude API (or any OpenAI-compatible API) for:
- NATO-format SITREP narrative generation from operational picture
- Natural language entity queries ("show me hostile vessels near Hormuz")
- Flash report generation from alerts

Falls back to template-based generation if no API key is configured.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger("mpe.intelligence")


# -- Template-based fallback (no API key needed) ----------------------------

SITREP_TEMPLATE = """SITUATION REPORT (SITREP)
Classification: UNCLASSIFIED
DTG: {dtg}
Reference: MPE-{ref}

1. SITUATION
   Air picture: {air_total} tracks ({air_friendly} friendly, {air_neutral} neutral, {air_hostile} hostile, {air_unknown} unknown)
   Maritime picture: {sea_total} tracks ({sea_friendly} friendly, {sea_neutral} neutral, {sea_hostile} hostile, {sea_unknown} unknown)
   Own forces: {own_total} assets active
   Active threats: {threat_count}
   Unacknowledged alerts: {alert_count}

2. THREAT SUMMARY
{threat_lines}

3. GEOFENCE STATUS
{geofence_lines}

4. ASSESSMENT
{assessment}

Generated by MPE C2 Intelligence Engine
"""


def generate_sitrep_template(sitrep_data: dict) -> str:
    """Generate a SITREP using templates (no LLM required)."""
    now = datetime.now(timezone.utc)
    summary = sitrep_data.get("summary", {})
    air = sitrep_data.get("air_picture", {}).get("by_affiliation", {})
    sea = sitrep_data.get("sea_picture", {}).get("by_affiliation", {})
    threats = sitrep_data.get("threats", [])

    threat_lines = "   No active threats." if not threats else ""
    for t in threats:
        threat_lines += (
            f"   - {t.get('callsign', 'UNKNOWN')} ({t.get('domain', '?')})"
            f" -- threat level {t.get('threat_level', 0)}/10,"
            f" {t.get('affiliation', 'unknown')}\n"
        )

    # Assessment
    threat_count = summary.get("active_threats", 0)
    if threat_count == 0:
        assessment = "   No significant threats detected. Normal operations."
    elif threat_count <= 3:
        assessment = (
            f"   {threat_count} threat(s) under monitoring."
            " Heightened awareness recommended."
        )
    else:
        assessment = (
            f"   {threat_count} active threats. Elevated threat posture."
            " Recommend increased surveillance."
        )

    return SITREP_TEMPLATE.format(
        dtg=now.strftime("%d%H%MZ %b %Y").upper(),
        ref=now.strftime("%Y%m%d-%H%M"),
        air_total=sitrep_data.get("air_picture", {}).get("total", 0),
        air_friendly=air.get("friendly", 0),
        air_neutral=air.get("neutral", 0),
        air_hostile=air.get("hostile", 0),
        air_unknown=air.get("unknown", 0),
        sea_total=sitrep_data.get("sea_picture", {}).get("total", 0),
        sea_friendly=sea.get("friendly", 0),
        sea_neutral=sea.get("neutral", 0),
        sea_hostile=sea.get("hostile", 0),
        sea_unknown=sea.get("unknown", 0),
        own_total=summary.get("own_forces", 0),
        threat_count=threat_count,
        alert_count=summary.get("unacknowledged_alerts", 0),
        threat_lines=threat_lines,
        geofence_lines="   No geofence violations.",
        assessment=assessment,
    )


# -- LLM-powered features --------------------------------------------------


class IntelligenceEngine:
    """LLM-powered intelligence analysis.

    Requires an API key for Claude or OpenAI-compatible API.
    Falls back to templates if no key is configured.
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str = "claude-sonnet-4-20250514",
    ):
        self._api_key = api_key
        self._model = model
        self._available = api_key is not None

    @property
    def is_available(self) -> bool:
        return self._available

    async def generate_sitrep(
        self, sitrep_data: dict, format: str = "nato",
    ) -> str:
        """Generate a SITREP narrative from operational picture data.

        Args:
            sitrep_data: The JSON from /api/operator/sitrep
            format: "nato" (formal SITREP), "flash" (one paragraph),
                    "brief" (3 bullets)
        """
        if not self._available:
            return generate_sitrep_template(sitrep_data)

        format_instructions = {
            "nato": (
                "Write a formal NATO-format SITREP with sections:"
                " SITUATION, ASSESSMENT, OUTLOOK. Use military terminology,"
                " grid references where available, and be concise."
            ),
            "flash": (
                "Write a single paragraph FLASH report highlighting the most"
                " critical information only. Maximum 3 sentences."
            ),
            "brief": (
                "Write exactly 3 bullet points summarizing the operational"
                " picture for a commander's briefing."
            ),
        }

        prompt = (
            "You are a military intelligence analyst generating a"
            " situation report.\n\n"
            f"Given this operational picture data:\n"
            f"{json.dumps(sitrep_data, indent=2, default=str)}\n\n"
            f"{format_instructions.get(format, format_instructions['nato'])}"
            "\n\nClassification: UNCLASSIFIED\n"
            "Be factual. Reference specific entities by callsign."
            " Include threat levels.\n"
            "Do not speculate beyond the data provided."
        )

        return await self._call_llm(prompt)

    async def natural_language_query(
        self,
        query: str,
        track_manager: object,
        geofence_manager: object | None = None,
    ) -> dict:
        """Process a natural language query against the operational picture.

        Examples:
        - "How many hostile vessels are near the Strait of Hormuz?"
        - "Show me all aircraft above 30000 feet"
        - "What's the threat level of AIS-273999111?"

        Returns a structured response with results and narrative.
        """
        # Build context from current picture
        active = track_manager.active_entities
        stats = track_manager.stats

        context = {
            "active_entities": len(active),
            "by_domain": stats.get("by_domain", {}),
            "threats": [
                {
                    "entity_id": e.entity_id,
                    "callsign": e.callsign or e.name,
                    "domain": e.domain,
                    "lat": e.latitude,
                    "lon": e.longitude,
                    "speed_mps": e.speed_mps,
                    "heading": e.heading,
                    "affiliation": e.affiliation,
                    "threat_level": e.threat_level,
                }
                for e in active
                if e.threat_level >= 4
            ],
            "sample_entities": [
                {
                    "entity_id": e.entity_id,
                    "callsign": e.callsign or e.name,
                    "domain": e.domain,
                    "lat": round(e.latitude, 4),
                    "lon": round(e.longitude, 4),
                    "affiliation": e.affiliation,
                    "threat_level": e.threat_level,
                }
                for e in active[:50]  # First 50 for context window
            ],
        }

        if not self._available:
            # Fallback: simple keyword matching
            return self._keyword_query(query, active)

        prompt = (
            "You are a C2 system intelligence analyst."
            " Answer the operator's query based on the operational picture."
            f"\n\nQUERY: {query}"
            f"\n\nOPERATIONAL PICTURE:\n"
            f"{json.dumps(context, indent=2, default=str)}"
            "\n\nRespond with a JSON object:\n"
            "{\n"
            '  "answer": "natural language answer to the query",\n'
            '  "entities_referenced": ["entity_id_1", "entity_id_2"],\n'
            '  "count": <number if the query asks for a count>,\n'
            '  "threat_assessment": "brief threat assessment if relevant"\n'
            "}\n\n"
            "Be precise. Only reference entities that exist in the data."
        )

        try:
            response_text = await self._call_llm(prompt)
            # Try to parse as JSON
            return json.loads(response_text)
        except (json.JSONDecodeError, Exception):
            return {
                "answer": response_text,
                "entities_referenced": [],
                "count": None,
            }

    def _keyword_query(self, query: str, entities: list) -> dict:
        """Simple keyword-based query fallback (no LLM)."""
        query_lower = query.lower()
        results = []

        # Domain filter
        if any(
            kw in query_lower
            for kw in ("aircraft", "air", "plane")
        ):
            results = [e for e in entities if e.domain == "air"]
        elif any(
            kw in query_lower
            for kw in ("vessel", "ship", "sea", "maritime")
        ):
            results = [e for e in entities if e.domain == "sea"]
        elif "drone" in query_lower:
            results = [
                e
                for e in entities
                if e.entity_type in ("uav", "fixed_wing")
                and e.affiliation == "friendly"
            ]

        # Affiliation filter
        if "hostile" in query_lower:
            results = [
                e for e in (results or entities) if e.affiliation == "hostile"
            ]
        elif "suspect" in query_lower:
            results = [
                e for e in (results or entities) if e.affiliation == "suspect"
            ]
        elif "friendly" in query_lower:
            results = [
                e
                for e in (results or entities)
                if e.affiliation == "friendly"
            ]

        # Threat filter
        if "threat" in query_lower:
            results = [
                e for e in (results or entities) if e.threat_level >= 4
            ]

        if not results:
            results = entities

        return {
            "answer": f"Found {len(results)} matching entities.",
            "entities_referenced": [e.entity_id for e in results[:20]],
            "count": len(results),
        }

    async def generate_flash_report(self, alert_event: object) -> str:
        """Generate a flash report from an alert event."""
        if not self._available:
            return f"FLASH: {alert_event.title}\n{alert_event.description}"

        prompt = (
            "Generate a one-paragraph military FLASH report for this alert:"
            f"\n\nTitle: {alert_event.title}"
            f"\nType: {alert_event.alert_type}"
            f"\nSeverity: {alert_event.severity}/10"
            f"\nEntity: {alert_event.entity_id}"
            f"\nPosition: {alert_event.latitude:.4f}N,"
            f" {alert_event.longitude:.4f}E"
            f"\nDescription: {alert_event.description}"
            "\n\nFormat: FLASH REPORT / DTG / WHAT / WHERE / ASSESSMENT"
            "\nBe concise. Maximum 4 sentences."
            " Classification: UNCLASSIFIED."
        )

        return await self._call_llm(prompt)

    async def _call_llm(self, prompt: str) -> str:
        """Call the Claude API. Uses urllib to avoid adding dependencies."""
        import urllib.request

        url = "https://api.anthropic.com/v1/messages"
        headers = {
            "Content-Type": "application/json",
            "x-api-key": self._api_key,
            "anthropic-version": "2023-06-01",
        }
        body = json.dumps({
            "model": self._model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}],
        })

        req = urllib.request.Request(
            url, data=body.encode(), headers=headers, method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                result = json.loads(resp.read())
                return result["content"][0]["text"]
        except Exception as e:
            logger.error("LLM call failed: %s", e)
            return f"[LLM unavailable: {e}]"
